/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.event.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Participant service. Represents a row in the &quot;rivetlogic_event_Participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.event.model.impl.ParticipantModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.event.model.impl.ParticipantImpl}.
 * </p>
 *
 * @author juancarrillo
 * @see Participant
 * @see com.rivetlogic.event.model.impl.ParticipantImpl
 * @see com.rivetlogic.event.model.impl.ParticipantModelImpl
 * @generated
 */
public interface ParticipantModel extends BaseModel<Participant> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a participant model instance should use the {@link Participant} interface instead.
	 */

	/**
	 * Returns the primary key of this participant.
	 *
	 * @return the primary key of this participant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this participant.
	 *
	 * @param primaryKey the primary key of this participant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this participant.
	 *
	 * @return the uuid of this participant
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this participant.
	 *
	 * @param uuid the uuid of this participant
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the participant ID of this participant.
	 *
	 * @return the participant ID of this participant
	 */
	public long getParticipantId();

	/**
	 * Sets the participant ID of this participant.
	 *
	 * @param participantId the participant ID of this participant
	 */
	public void setParticipantId(long participantId);

	/**
	 * Returns the company ID of this participant.
	 *
	 * @return the company ID of this participant
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this participant.
	 *
	 * @param companyId the company ID of this participant
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this participant.
	 *
	 * @return the group ID of this participant
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this participant.
	 *
	 * @param groupId the group ID of this participant
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the event ID of this participant.
	 *
	 * @return the event ID of this participant
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this participant.
	 *
	 * @param eventId the event ID of this participant
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the full name of this participant.
	 *
	 * @return the full name of this participant
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this participant.
	 *
	 * @param fullName the full name of this participant
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the email of this participant.
	 *
	 * @return the email of this participant
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this participant.
	 *
	 * @param email the email of this participant
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone number of this participant.
	 *
	 * @return the phone number of this participant
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this participant.
	 *
	 * @param phoneNumber the phone number of this participant
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the company name of this participant.
	 *
	 * @return the company name of this participant
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this participant.
	 *
	 * @param companyName the company name of this participant
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the status of this participant.
	 *
	 * @return the status of this participant
	 */
	public int getStatus();

	/**
	 * Sets the status of this participant.
	 *
	 * @param status the status of this participant
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Participant participant);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Participant> toCacheModel();

	@Override
	public Participant toEscapedModel();

	@Override
	public Participant toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}