/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.event.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Token service. Represents a row in the &quot;rivetlogic_event_Token&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.event.model.impl.TokenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.event.model.impl.TokenImpl}.
 * </p>
 *
 * @author juancarrillo
 * @see Token
 * @see com.rivetlogic.event.model.impl.TokenImpl
 * @see com.rivetlogic.event.model.impl.TokenModelImpl
 * @generated
 */
public interface TokenModel extends BaseModel<Token> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a token model instance should use the {@link Token} interface instead.
	 */

	/**
	 * Returns the primary key of this token.
	 *
	 * @return the primary key of this token
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this token.
	 *
	 * @param primaryKey the primary key of this token
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this token.
	 *
	 * @return the uuid of this token
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this token.
	 *
	 * @param uuid the uuid of this token
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the token ID of this token.
	 *
	 * @return the token ID of this token
	 */
	public long getTokenId();

	/**
	 * Sets the token ID of this token.
	 *
	 * @param tokenId the token ID of this token
	 */
	public void setTokenId(long tokenId);

	/**
	 * Returns the participant ID of this token.
	 *
	 * @return the participant ID of this token
	 */
	public long getParticipantId();

	/**
	 * Sets the participant ID of this token.
	 *
	 * @param participantId the participant ID of this token
	 */
	public void setParticipantId(long participantId);

	/**
	 * Returns the expired date of this token.
	 *
	 * @return the expired date of this token
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this token.
	 *
	 * @param expiredDate the expired date of this token
	 */
	public void setExpiredDate(Date expiredDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Token token);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Token> toCacheModel();

	@Override
	public Token toEscapedModel();

	@Override
	public Token toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}